[tools]
# Production
go = "1.27.2"

# Development
"npm:@biomejs/biome" = "latest"
"go:github.com/a-h/templ/cmd/templ" = { version = "latest", minimum_release_age = "0" }
golangci-lint = "latest"
staticcheck = "latest"
"go:golang.org/x/tools/gopls" = "latest"
uv = "latest"
semgrep = "latest"
shellcheck = "latest"

# Test
node = "lts"
jq = "latest"
yq = "latest"
"github:lightpanda-io/browser" = { version = "latest", rename_exe = "lightpanda", minimum_release_age = "0", prerelease = true, version_order = "semver" }

[settings]
minimum_release_age = "7d"

[settings.npm]
package_manager = "npm"
