[tools]
# Production
go = "1.27.1"

# Development
"npm:@biomejs/biome" = "2.5.13"
golangci-lint = "latest"
staticcheck = "latest"
"go:golang.org/x/tools/gopls" = "latest"
uv = "latest"
semgrep = "latest"
shellcheck = "latest"

# Test
node = "lts"
jq = "latest"
yq = "latest"

[settings]
minimum_release_age = "7d"

[settings.npm]
package_manager = "npm"
