FROM docker.io/debian:trixie-slim

WORKDIR /infinite

RUN apt-get update && apt-get upgrade -y \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y bind9-dnsutils build-essential ca-certificates certbot cron \
	curl debian-archive-keyring git gnupg2 haveged lsb-release procps rsync supervisor \
	tar unzip vim wget zip unattended-upgrades

RUN curl -skL "https://nginx.org/keys/nginx_signing.key" | gpg --dearmor >"/usr/share/keyrings/nginx-archive-keyring.gpg" \
	&& echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian $(lsb_release -cs) nginx" >"/etc/apt/sources.list.d/nginx.list" \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y nginx \
	&& mkdir -p /app/conf/pki \
	&& chown -R nobody:nogroup /app

RUN curl -skL "https://mise.run" \
	| MISE_INSTALL_PATH=/usr/local/bin/mise sh \
	&& chmod +x /usr/local/bin/mise \
	&& echo 'eval "$(/usr/local/bin/mise activate bash)"' >>/etc/profile

ENV MISE_DATA_DIR=/usr/local/share/mise

COPY . .

COPY /container/nginx/root/* /etc/nginx/

COPY --chown=nobody:nogroup /container/nginx/user/ /app/conf/nginx/

COPY /container/supervisord.conf /infinite/supervisord.conf

RUN wget -qO go.tar.gz "https://go.dev/dl/go1.26.5.linux-amd64.tar.gz" \
	&& tar -C /usr/local -xzf go.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}"

RUN go mod download \
	&& go build -o os

ENTRYPOINT ["go", "test", "-v", "./..."]
