FROM docker.io/bitnami/minideb:bullseye-amd64

WORKDIR /speedia

RUN install_packages ca-certificates wget curl tar procps cron \
    && touch /var/spool/cron/crontabs/root

RUN wget -nv https://go.dev/dl/go1.20.5.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}"

COPY . .

RUN go mod download \
    && go build -o sos

ENTRYPOINT ["go", "test", "-v", "./..."]