name: php-webserver
slugs:
  - php-webserver
  - php-ws
  - php
nature: solo
type: runtime
description: PHP is a general-purpose scripting language geared towards web development. OpenLiteSpeed (PHP WebServer) is a high-performance, lightweight, open source HTTP (and PHP) server developed and copyrighted by LiteSpeed Technologies.
versions:
  - latest
portBindings:
  - 8080/http
  - 8443/https
startCmd: /usr/local/lsws/bin/litespeed -d
installCmdSteps:
  - curl -skL https://repo.litespeed.sh | bash
  - install_packages openlitespeed
  - for v in "74" "80" "81" "82" "83"; do install_packages lsphp${v} lsphp${v}-common lsphp${v}-curl lsphp${v}-intl lsphp${v}-mysql lsphp${v}-opcache; done
  - ln -s /usr/local/lsws/lsphp82/bin/php /usr/bin/php
  - curl -skL -o /usr/local/lsws/conf/httpd_config.conf https://speedia.net/assets/os/services/php-webserver/httpd_config.conf
  - sed -i "s/speedia.net/%primaryHostname%/g" /usr/local/lsws/conf/httpd_config.conf
  - curl -skL -o /app/conf/php-webserver/template https://speedia.net/assets/os/services/php-webserver/primary.conf
  - cp /app/conf/php-webserver/template /app/conf/php-webserver/primary.conf
  - sed -i "s/speedia.net/%primaryHostname%/g" /app/conf/php-webserver/primary.conf
  - chown -R lsadm:nogroup /app/conf/php-webserver/
  - chown -R nobody:nogroup /app/logs/php-webserver
  - /speedia/os cron create -s "*/2 * * * *" -d "AutoReloadPhpWebServerAfterHtaccessChange" -c "if ! find /app/html -maxdepth 7 -type f -name '.htaccess' -newer /usr/local/lsws/cgid -exec false {} +; then /speedia/os services update -n php-webserver -s restart; fi"
uninstallCmdSteps:
  - /speedia/os cron delete -d "AutoReloadPhpWebServerAfterHtaccessChange"
  - if [[ -f "/usr/bin/php" ]]; then unlink /usr/bin/php; fi
  - apt-get purge -y openlitespeed lsphp*
stopCmdSteps:
  - sleep 1; if pgrep litespeed >/dev/null; then /usr/local/lsws/bin/lswsctrl stop; fi
  - if pgrep lsphp >/dev/null; then pkill lsphp; fi
estimatedSizeBytes: 157286400
avatarUrl: https://speedia.net/assets/os/services/php-webserver/php-webserver-avatar.jpg
