package infraEnvs

const (
	InfiniteOsVersion                  string = "0.3.1"
	InfiniteOsMainDir                  string = "/infinite"
	InfiniteOsBinary                   string = InfiniteOsMainDir + "/os"
	InfiniteOsEnvFilePath              string = InfiniteOsMainDir + "/.env"
	InfiniteOsApiHttpPublicPort        string = "1618"
	PersistentDatabaseFilePath         string = InfiniteOsMainDir + "/os.db"
	PersistentDatabaseConnectionParams string = "?cache=shared&mode=rwc&_journal_mode=WAL&_busy_timeout=5000&_foreign_keys=on"
	TrailDatabaseFilePath              string = InfiniteOsMainDir + "/trail.db"
	MarketplaceCatalogItemsDir         string = InfiniteOsMainDir + "/marketplace"
	MarketplaceCatalogItemsRepoUrl     string = "https://github.com/goinfinite/os-marketplace"
	MarketplaceCatalogItemsRepoBranch  string = "v2"
	InstallableServicesItemsDir        string = InfiniteOsMainDir + "/services"
	InstallableServicesItemsRepoUrl    string = "https://github.com/goinfinite/os-services"
	InstallableServicesItemsRepoBranch string = "v1"
	VirtualHostsConfDir                string = "/app/conf/nginx"
	PrimaryVirtualHostEnvKey           string = "PRIMARY_VHOST"
	PrimaryVirtualHostPublicDir        string = "/app/html"
	PrimaryVirtualHostConfPath         string = VirtualHostsConfDir + "/primary.conf"
	MappingsConfDir                    string = VirtualHostsConfDir + "/mapping"
	MappingsSecurityRulesConfDir       string = MappingsConfDir + "/security"
	PkiConfDir                         string = "/app/conf/pki"
	WebServerBinaryPath                string = "/usr/sbin/nginx"
	WebServerMainConfPath              string = "/etc/nginx/nginx.conf"
	PhpWebserverMainConfFilePath       string = "/usr/local/lsws/conf/httpd_config.conf"
	PhpWebserverUsername               string = "nobody"
	PhpWebserverGroupName              string = "nogroup"
	AccessTokenCookieKey               string = "os-access-token"
	UserDataBaseDirectory              string = "/home"
	DefaultPrimaryVhost                string = "goinfinite.local"
	LocalStatesAssetsPath              string = "/assets/local-states"
	GlobalStatesAssetsPath             string = "/assets/global-states"
)
