package infraEnvs

const (
	InfiniteOsVersion                  string = "0.2.5"
	InfiniteOsMainDir                  string = "/infinite"
	InfiniteOsBinary                   string = InfiniteOsMainDir + "/os"
	InfiniteOsEnvFilePath              string = InfiniteOsMainDir + "/.env"
	InfiniteOsApiHttpPublicPort        string = "1618"
	PersistentDatabaseFilePath         string = InfiniteOsMainDir + "/os.db"
	TrailDatabaseFilePath              string = InfiniteOsMainDir + "/trail.db"
	MarketplaceCatalogItemsDir         string = InfiniteOsMainDir + "/marketplace"
	MarketplaceCatalogItemsRepoUrl     string = "https://github.com/goinfinite/os-marketplace"
	MarketplaceCatalogItemsRepoBranch  string = "v1"
	InstallableServicesItemsDir        string = InfiniteOsMainDir + "/services"
	InstallableServicesItemsRepoUrl    string = "https://github.com/goinfinite/os-services"
	InstallableServicesItemsRepoBranch string = "v1"
	PrimaryPublicDir                   string = "/app/html"
	VirtualHostsConfDir                string = "/app/conf/nginx"
	MappingsConfDir                    string = VirtualHostsConfDir + "/mapping"
	MappingsSecurityRulesConfDir       string = MappingsConfDir + "/security"
	PkiConfDir                         string = "/app/conf/pki"
	PhpWebserverMainConfFilePath       string = "/usr/local/lsws/conf/httpd_config.conf"
	AccessTokenCookieKey               string = "os-access-token"
	UserDataBaseDirectory              string = "/home"
	DefaultPrimaryVhost                string = "goinfinite.local"
	LocalStatesAssetsPath              string = "/assets/local-states"
	GlobalStatesAssetsPath             string = "/assets/global-states"
)
